// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/admissions-dashboard/CleanSaaS.tsx": () => import("../components/mockups/admissions-dashboard/CleanSaaS.tsx"),
  "./components/mockups/admissions-dashboard/CommandCenter.tsx": () => import("../components/mockups/admissions-dashboard/CommandCenter.tsx")
};
